<?php
/**
 * includes/lang.php - Localization Data
 * Contains the dictionary of all UI strings used throughout the application.
 * Note: This version is hardcoded to English only as per project requirements.
 */

/**
 * Translation function. Retrieves a string by its key from the internal dictionary.
 * 
 * @param string $key The translation key.
 * @return string The translated string or the key if not found.
 */
function t($key) {
    $translations = [
        // ========== GENERAL UI ==========
        'dashboard' => 'Dashboard',
        'equipment' => 'Equipment',
        'interventions' => 'Interventions',
        'preventive_maintenance' => 'Preventive Maintenance',
        'stock' => 'Spare Parts',
        'technicians' => 'Technicians',
        'planning' => 'Planning',
        'alerts' => 'Alerts',
        'performance_analysis' => 'Performance Analysis',
        'email_config' => 'Email Configuration',
        'users' => 'Users',
        'profile' => 'My Profile',
        'logout' => 'Logout',
        'back' => 'Back',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'delete' => 'Delete',
        'edit' => 'Edit',
        'view' => 'View',
        'add' => 'Add',
        'search' => 'Search',
        'filter' => 'Filter',
        'export' => 'Export',
        'import' => 'Import',
        'yes' => 'Yes',
        'no' => 'No',
        'close' => 'Close',
        'confirm' => 'Confirm',
        'status' => 'Status',
        'actions' => 'Actions',
        'date' => 'Date',
        'created_at' => 'Created at',
        'new_intervention' => 'New Intervention',
        'add_equipment' => 'Add Equipment',
        'plan_maintenance' => 'Plan Maintenance',
        'recent_interventions' => 'Recent Interventions',
        'quick_actions' => 'Quick Actions',
        'advanced_analysis' => 'Advanced Analysis',
        'view_performance' => 'View Performance Analysis',
        'no_alerts' => 'No alerts to report',
        'all' => 'All',
        'total' => 'Total',
        'details' => 'Details',
        'by' => 'By',
        'unknown' => 'Unknown',
        'not_specified' => 'Not specified',
        'never' => 'Never',
        'expired' => 'Expired',
        'expiring_soon' => 'Expiring soon',
        'references' => 'References',
        'per_intervention' => 'Per intervention',
        'no_interventions' => 'No interventions',
        'admin' => 'Admin',
        'on' => 'on',
        'technician_detail' => 'Technician Details',
        'popup_notifications' => 'Popup Notifications',
        'popup_settings_desc' => 'Show popup alerts when new events occur',
        'preference_saved' => 'Preference saved',
        'critical_alerts' => 'Critical Alerts',
        'warning_alerts' => 'Warning Alerts',
        'info_alerts' => 'Information',
        'type' => 'Type',
        'message' => 'Message',
        'priority' => 'Priority',
        
        // ========== LOGIN & SECURITY ==========
        'login_title' => 'GMAO Industrial',
        'login_subtitle' => 'Maintenance Management System',
        'username' => 'Username',
        'password' => 'Password',
        'login' => 'Login',
        'demo_accounts' => 'Demo accounts',
        'account_disabled' => 'Account disabled',
        'login_success' => 'Login successful',
        'login_error' => 'Invalid credentials',
        'save_success' => 'Save successful',
        'save_error' => 'Save error',
        'delete_confirm' => 'Are you sure you want to delete?',
        'delete_warning' => 'This action is irreversible.',
        'password_error' => 'Incorrect password',
        'password_match' => 'Passwords match',
        'password_mismatch' => 'Passwords do not match',
        'password_too_short' => 'Password must be at least 6 characters',
        'access_denied' => 'Access denied',
        'restore_confirm' => 'Are you sure you want to restore?',
        'delete_equipment' => 'Delete Equipment',
        'restore' => 'Restore',
        
        // ========== EQUIPMENT ==========
        'code' => 'Code',
        'name' => 'Name',
        'type' => 'Type',
        'location' => 'Location',
        'supplier' => 'Supplier',
        'purchase_date' => 'Purchase Date',
        'warranty_end' => 'Warranty End',
        'technical_specs' => 'Technical Specifications',
        'qr_code' => 'QR Code',
        'scan_qr' => 'Scan QR Code',
        'equipment_list' => 'Equipment List',
        'add_equipment' => 'Add Equipment',
        'edit_equipment' => 'Edit Equipment',
        'equipment_detail' => 'Equipment Details',
        'active' => 'Active',
        'maintenance' => 'Maintenance',
        'broken' => 'Broken',
        'retired' => 'Retired',
        'equipment_not_found' => 'Equipment not found',
        'general_info' => 'General Information',
        'dates' => 'Dates',
        'interventions_history' => 'Interventions History',
        'preventive_maintenances' => 'Preventive Maintenances',
        'modifications_history' => 'Modifications History',
        'created' => 'Created',
        'modified' => 'Modified',
        'deactivated' => 'Deactivated',
        'restored' => 'Restored',
        'view_equipment' => 'View Equipment',
        'qr_code_for' => 'QR Code for',
        'print_label' => 'Print label',
        'last_interventions' => 'Last interventions',
        'scan_qr_instruction' => 'Scan this QR code with your smartphone to quickly access equipment information',
        'active_description' => 'Available for assignments',
        'maintenance_description' => 'Currently under maintenance',
        'broken_description' => 'Equipment is broken',
        'retired_description' => 'Equipment is retired',
        'no_history' => 'No history recorded',
        
        // ========== INTERVENTIONS ==========
        'total_interventions' => 'Total Interventions',
        'task_number' => 'Task Number',
        'title' => 'Title',
        'description' => 'Description',
        'priority' => 'Priority',
        'critical' => 'Critical',
        'high' => 'High',
        'medium' => 'Medium',
        'low' => 'Low',
        'pending' => 'Pending',
        'in_progress' => 'In Progress',
        'completed' => 'Completed',
        'closed' => 'Closed',
        'assigned_to' => 'Assigned To',
        'planned_date' => 'Planned Date',
        'duration' => 'Duration',
        'report' => 'Report',
        'intervention_list' => 'Interventions List',
        'add_intervention' => 'Add Intervention',
        'edit_intervention' => 'Edit Intervention',
        'intervention_details' => 'Intervention Details',
        'corrective' => 'Corrective',
        'preventive' => 'Preventive',
        'emergency' => 'Emergency',
        'to_do' => 'To Do',
        'in_progress_status' => 'In Progress',
        'completed_status' => 'Completed',
        'closed_status' => 'Closed',
        'intervention_not_found' => 'Intervention not found',
        'created_by' => 'Created by',
        'actual_duration' => 'Actual duration',
        'completion_date' => 'Completion date',
        'completion_report' => 'Completion Report',
        'parts_used' => 'Parts used',
        'total_cost' => 'Total cost',
        'complete_intervention' => 'Complete Intervention',
        'cancel_intervention' => 'Cancel Intervention',
        'identification' => 'Identification',
        'equipment_and_location' => 'Equipment and Location',
        'organisation' => 'Organization',
        'classification' => 'Classification',
        'intervention_type' => 'Intervention Type',
        'create_intervention' => 'Create Intervention',
        'auto_increment' => 'Automatic incremented number',
        'current_datetime' => 'Current date and time',
        'zone_placeholder' => 'Ex: Building A, Workshop 3...',
        'localisation_placeholder' => 'Ex: Room 231, Press #2...',
        'description_placeholder' => 'Describe the intervention, the problem observed...',
        'select_equipment' => 'Select equipment',
        'no_description' => 'No description',
        'no_technician_assigned' => 'No technician assigned',
        'view_details' => 'View details',
        'status_changed' => 'Status changed',
        'assigned' => 'Assigned',
        'cancelled' => 'Cancelled',
        'hours' => 'hours',
        'not_planned' => 'Not planned',
        'intervention_created' => 'Intervention created',
        'intervention_view' => 'Intervention View',
        'upcoming_interventions' => 'Upcoming Interventions',
        
        // ========== TECHNICIANS ==========
        'employee_id' => 'Employee ID',
        'firstname' => 'First Name',
        'lastname' => 'Last Name',
        'phone' => 'Phone',
        'email' => 'Email',
        'specialty' => 'Specialty',
        'hire_date' => 'Hire Date',
        'active' => 'Active',
        'active_interventions' => 'Active Interventions',
        'last_modifications' => 'Last Modifications',
        'inactive' => 'Inactive',
        'on_leave' => 'On Leave',
        'technician_list' => 'Technicians List',
        'add_technician' => 'Add Technician',
        'edit_technician' => 'Edit Technician',
        'technician_details' => 'Technician Details',
        'completion_rate' => 'Completion Rate',
        'avg_duration' => 'Avg Duration',
        'technician_not_found' => 'Technician not found',
        'personal_info' => 'Personal Information',
        'skills' => 'Skills',
        'no_skills' => 'No skills recorded',
        'expert' => 'Expert',
        'advanced' => 'Advanced',
        'intermediate' => 'Intermediate',
        'beginner' => 'Beginner',
        'certified' => 'Certified',
        'seniority' => 'Seniority',
        'years' => 'years',
        'in_progress_interventions' => 'In Progress Interventions',
        'weekly_schedule' => 'Weekly Schedule',
        'view_schedule' => 'View schedule',
        'deactivate' => 'Deactivate',
        'deactivate_confirm' => 'Deactivate this technician?\n\nHe will no longer be available for assignments.',
        'technicians_active' => 'Active Technicians',
        'specialty_placeholder' => 'Ex: Electrician, Mechanic...',
        'delete_warning_technician' => 'The technician will no longer be available for assignments but will remain in the history.',
        'active_desc' => 'Available for assignments',
        'on_leave_desc' => 'Temporarily unavailable',
        'inactive_desc' => 'No longer active',
        'not_provided' => 'Not provided',
        'year_s' => 'year(s)',
        'month_s' => 'month(s)',
        'performance_stats' => 'Performance Statistics',
        'no_upcoming' => 'No upcoming interventions',
        'view_technicians' => 'Back to technicians list',
        
        'monday' => 'Monday',
        'tuesday' => 'Tuesday',
        'wednesday' => 'Wednesday',
        'thursday' => 'Thursday',
        'friday' => 'Friday',
        'saturday' => 'Saturday',
        'sunday' => 'Sunday',
        'interv_short' => 'interv.',
        'view_planning' => 'View planning',
        'deactivate_technician' => 'Deactivate technician',
        'deactivate_technician_confirm' => 'Are you sure you want to deactivate this technician?\n\nHe will no longer be available for assignments.',
        
        // ========== STOCK ==========
        'part_number' => 'Part Number',
        'quantity' => 'Quantity',
        'min_quantity' => 'Min Quantity',
        'unit_price' => 'Unit Price',
        'location_stock' => 'Location',
        'stock_list' => 'Stock List',
        'add_part' => 'Add Part',
        'edit_part' => 'Edit Part',
        'stock_in' => 'Stock In',
        'stock_out' => 'Stock Out',
        'critical_stock' => 'Critical Stock',
        'to_monitor' => 'To Monitor',
        'sufficient' => 'Sufficient',
        'documentation' => 'Documentation',
        'part_not_found' => 'Part not found',
        'stock_status' => 'Stock Status',
        'current_stock' => 'Current stock',
        'recommended_stock' => 'Recommended stock',
        'movements_history' => 'Movements History',
        'no_movements' => 'No movements recorded',
        'total_movements' => 'Total movements',
        'reason' => 'Reason',
        'reason_placeholder' => 'Ex: Order #1234, Return...',
        'quantity_to_add' => 'Quantity to add',
        'quantity_to_remove' => 'Quantity to remove',
        'file_path' => 'File path',
        'open_doc' => 'Open documentation',
        'critical_desc' => 'Quantity < minimum threshold',
        'monitor_desc' => 'Quantity < 2x minimum threshold',
        'sufficient_desc' => 'Sufficient stock',
        'inactive_desc' => 'Deactivated part',
        'movement' => 'Movement',
        'part' => 'Part',
        'stock_insufficient' => 'Insufficient stock',
        'doc_placeholder' => 'Ex: C:\\Docs\\fiche.pdf',
        'doc_help' => 'Full path to documentation file/folder',
        'open' => 'Open',
        'stock_level' => 'Stock Level',
        
        // ========== PREVENTIVE MAINTENANCE ==========
        'every' => 'Every',
        'days' => 'days',
        'months' => 'months',
        'weeks' => 'weeks',
        'team' => 'Team',
        'validate' => 'Validate',
        'validate_confirm' => 'Validate this maintenance as completed?',
        'not_found' => 'Not found',
        'overdue' => 'Overdue',
        'upcoming' => 'Upcoming',
        'ok' => 'OK',
        'only' => 'only',
        'units' => 'units',
        'days_ago' => 'days ago',
        'days_left' => 'days left',
        'frequency_help' => 'Examples: 30 days (monthly), 90 days (quarterly), 365 days (yearly)',
        'team_placeholder' => 'Ex: Team A, Maintenance department...',
        'instructions_placeholder' => 'Describe the operations to perform, checks to carry out...',
        'add_maintenance' => 'Add Maintenance',
        'edit_maintenance' => 'Edit Maintenance',
        'delete_maintenance' => 'Delete Maintenance',
        'maintenance_list' => 'Maintenance Schedule',
        'overdue_by' => 'Overdue by',
        'in' => 'In',
        'last_done' => 'Last Done',
        'next_due' => 'Next Due',
        'instructions' => 'Instructions',
        'assigned_team' => 'Assigned Team',
        'frequency_days' => 'Frequency (days)',
        
        // ========== ALERTS ==========
        'alert_center' => 'Alert Center',
        'critical_alerts' => 'Critical Alerts',
        'warning_alerts' => 'Warning Alerts',
        'info_alerts' => 'Information',
        'total_alerts' => 'Total Alerts',
        'critical_intervention' => '🚨 Critical Intervention',
        'maintenance_overdue' => '⚠️ Overdue Maintenance',
        'maintenance_upcoming' => 'Upcoming Maintenance',
        'stock_critical_title' => '📦 Critical Stock Alert',
        'low_stock_title' => '⚠️ Low Stock',
        'remaining' => 'remaining',
        'warranty_expired' => '⚠️ Warranty Expired',
        'warranty_upcoming' => '📅 Warranty Expiring Soon',
        'days_left' => 'days left',
        'unassigned_intervention_title' => 'Unassigned Intervention',
        'critical_interventions_title' => 'Critical Interventions',
        'maintenance_overdue_title' => 'Overdue Maintenances',
        'maintenance_upcoming_title' => 'Upcoming Maintenances',
        'warranty_expired_title' => '⚠️ Warranty Expired',
        'warranty_upcoming_title' => '📅 Warranty Expiring Soon',
        'unassigned_intervention_title' => '📋 Unassigned Intervention',
        'created_on' => 'Created on',
        'delay' => 'Delay of',
        'expired_since' => 'Expired since',
        'expires_in' => 'Expires in',
        'waiting_assignment' => 'Waiting for assignment for',
        'stock_at' => 'Stock at',
        'mark_all_read' => 'Mark all as read',
        'mark_all_read_confirm' => 'Mark all alerts as read for this session?\n\nThey will reappear if the causes persist after refresh.',
        'alerts_hidden_session' => 'All alerts have been hidden for this session. They will reappear if the causes persist after refresh.',
        'mark_as_read' => 'Mark as read',
        'warning' => 'Warning',
        'info' => 'Information',
        'excellent' => 'Excellent!',
        'alerts_active' => 'active alerts',
        'new_equipment_count' => 'New equipment',
        'view_stock' => 'View stock',
        'view_in_gmao' => 'View in GMAO',
        'access_dashboard' => 'Access Dashboard',
        'automatic_message' => 'Automatic message sent by Industrial GMAO',
        'overdue_by' => 'Overdue by',
        'only' => 'only',
        'units' => 'units left',
        'on' => 'on',
        'waiting_assignment' => 'Waiting for assignment for',
        'days_ago' => 'day(s) ago',
        'days_left' => 'day(s) left',
        'warranty_expired' => 'Expired',
        'critical_intervention' => '🚨 Critical Intervention',
        'count_days' => 'day(s)',
        'for' => 'for',
        'minutes' => 'minutes',
        'hours' => 'hours',
        'gmao_alerts' => 'GMAO Alerts',
        'no_alerts' => 'No new alerts',
        'view_all_alerts' => 'View all alerts',
        'unauthenticated' => 'Unauthenticated',
        'popup_notifications' => 'Popup Notifications',
        'popup_settings_desc' => 'Show popup alerts when new events occur',
        'critical_alerts' => 'Critical Alerts',
        'warning_alerts' => 'Warning Alerts',
        'info_alerts' => 'Information',
        'total_alerts' => 'Total Alerts',
        'critical_interventions_title' => 'Critical Interventions',
        'maintenance_overdue_title' => 'Overdue Maintenances',
        'maintenance_upcoming_title' => 'Upcoming Maintenances',
        'stock_critical_title' => 'Critical Stock',
        'warranty_expired_title' => 'Expired Warranties',
        'warranty_upcoming_title' => 'Warranties Expiring Soon',
        'unassigned_intervention_title' => 'Unassigned Interventions',
        'mark_all_read' => 'Mark all as read',
        'mark_all_read_confirm' => 'Mark all alerts as read for this session?',
        'alerts_hidden_session' => 'All alerts have been hidden for this session.',
        'excellent' => 'Excellent!',
        'no_alerts' => 'No alerts to display',
        'stock_at' => 'Stock at',
        'expires_in' => 'Expires in',
        'expired_since' => 'Expired since',
        'delay' => 'Delay of',
        'waiting_assignment' => 'Waiting for assignment for',
        
        // ========== PERFORMANCE ==========
        'mtbf' => 'MTBF',
        'mttr' => 'MTTR',
        'availability' => 'Availability',
        'mtbf_description' => 'Mean Time Between Failures',
        'mttr_description' => 'Mean Time To Repair',
        'availability_description' => 'Equipment availability rate',
        'mtbf_trend' => 'MTBF Trend (6 months)',
        'failures_by_type' => 'Failures by Equipment Type',
        'top_problematic' => 'Top 5 Problematic Equipment',
        'best_performers' => 'Best Performers',
        'critical_equipment' => 'Critical Equipment',
        'detailed_performance' => 'Detailed Equipment Performance',
        'recommendations' => 'Recommendations',
        'major_overhaul' => 'Major overhaul recommended',
        'training_recommendation' => 'Train technicians on this equipment',
        'reinforced_preventive' => 'Reinforced preventive maintenance',
        'global_mtbf_low' => 'Global MTBF is low - Review maintenance strategy',
        'global_mttr_high' => 'Global MTTR is high - Improve repair processes',
        'perfect_performance' => 'Perfect performance! Continue like this',
        'failures_count' => 'Number of failures',
        'unclassified' => 'Unclassified',
        'total_failures' => 'Total Failures',
        'failures_recorded' => 'Failures recorded',
        'urgent_revision' => 'Urgent revision',
        'monitoring' => 'Monitoring',
        'good' => 'Good',
        'average' => 'Average',
        'mtbf_mttr_indicators' => 'MTBF/MTTR Indicators',
        'advanced_dashboard' => 'Advanced Dashboard',
        'global_mtbf' => 'Global MTBF',
        'global_mttr' => 'Global MTTR',
        'mtbf_short_desc' => 'Mean time between failures',
        'mttr_short_desc' => 'Mean time to repair',
        'mtbf_trend_6m' => 'MTBF Evolution (last 6 months)',
        'equipment_performance' => 'Equipment Performance',
        'excellent_performance' => 'All equipment has good performance. Continue like this!',
        'failures_by_type_pie' => 'Failures by equipment type',
        
        // ========== USERS ==========
        'user_list' => 'Users List',
        'add_user' => 'Add User',
        'edit_user' => 'Edit User',
        'reset_password' => 'Reset Password',
        'confirm_password' => 'Confirm Password',
        'new_password' => 'New Password',
        'current_password' => 'Current Password',
        'role' => 'Role',
        'supervisor' => 'Supervisor',
        'technician_role' => 'Technician',
        'viewer' => 'Viewer',
        'action_log' => 'Action Log',
        'protected' => 'Protected',
        'login_success_log' => 'Successful login',
        'user_created_log' => 'User created',
        'user_updated_log' => 'User updated',
        'user_deleted_log' => 'User deleted',
        'password_reset_log' => 'Password reset',
        'profile_updated_log' => 'Profile updated',
        'no_logs' => 'No logs recorded',
        'delete_error' => 'Cannot delete this user',
        'fullname' => 'Full name',
        'last_connection' => 'Last connection',
        'member_since' => 'Member since',
        'update_profile' => 'Update Profile',
        'change_password' => 'Change Password',
        'select_language' => 'Select Language',
        'french' => 'French',
        'english' => 'English',
        'language_updated' => 'Language updated',
        
        // ========== EMAIL & SMTP ==========
        'smtp_settings' => 'SMTP Settings',
        'smtp_host' => 'SMTP Host',
        'smtp_port' => 'SMTP Port',
        'smtp_user' => 'SMTP User',
        'smtp_password' => 'SMTP Password',
        'smtp_secure' => 'Security',
        'tls' => 'TLS (recommended)',
        'ssl' => 'SSL',
        'none' => 'None',
        'sender_email' => 'Sender Email',
        'sender_name' => 'Sender Name',
        'alert_recipients' => 'Alert Recipients',
        'test_email' => 'Test Email',
        'save_and_test' => 'Save and Test',
        'reset' => 'Reset',
        'help' => 'Help',
        'common_providers' => 'Common SMTP Providers',
        'automatic_alerts' => 'Automatic Alerts',
        'alerts_description' => 'The following alerts will be sent automatically',
        'weekly_reports' => 'Weekly reports',
        'alerts_check_hourly' => 'Alerts are checked automatically every hour',
        'reset_confirm' => 'Reset all form fields?',
        'test_email_subject' => 'GMAO Test - Email configuration successful',
        'test_email_success' => 'Test successful!',
        'test_email_message' => 'Your email configuration is working correctly.',
        'test_email_date' => 'Test date',
        'test_email_sent' => 'Test email sent to',
        'test_email_failed' => 'The test email could not be sent. Check your SMTP configuration.',
        'smtp_host_help' => 'Ex: smtp.gmail.com, smtp.office365.com',
        'smtp_port_help' => '587 for TLS, 465 for SSL',
        'smtp_password_help' => 'For Gmail, use an app password',
        'port' => 'Port',
        'alert_recipients_help' => 'Separate addresses with commas',
        'test_email_help' => 'Leave empty to not send a test',
        
        // ========== EXPORT & IMPORT ==========
        'export_center' => 'Export Center',
        'export_interventions_excel' => 'Export Interventions - Excel',
        'export_interventions_desc' => 'Export the list of interventions in Excel format (.xlsx)',
        'export_equipment_excel' => 'Export Equipment - Excel',
        'export_equipment_desc' => 'Export the list of equipment in Excel format (.xlsx)',
        'export_stock_excel' => 'Export Stock - Excel',
        'export_stock_desc' => 'Export the spare parts inventory in Excel format (.xlsx)',
        'export_pdf_report' => 'Export PDF Report',
        'export_pdf_desc' => 'Generate a detailed PDF report for an intervention',
        'task_number_or_id' => 'Task number or ID',
        'task_number_placeholder' => 'Ex: TASK-260032 or ID',
        'export_pdf_help' => 'You can also click the eye icon in the interventions list',
        'view_interventions' => 'View all interventions',
        'import_csv' => 'Import CSV',
        'import_csv_desc' => 'Import equipment from a CSV file',
        'csv_format_info' => 'Expected format:',
        'access_import' => 'Access CSV import',
        'export_csv_interventions' => 'Export CSV - Interventions',
        'export_csv_desc' => 'Export interventions in CSV format for external processing',
        'export_csv' => 'Export CSV',
        'export_excel' => 'Export Excel',
        'export_ical_desc' => 'Export the calendar to iCal format for Outlook/Google Calendar',
        'information' => 'Information',
        'excel_exports' => 'Excel Exports',
        'excel_exports_desc' => 'Excel files are generated in .xlsx format and can be opened with Microsoft Excel, LibreOffice Calc or Google Sheets',
        'pdf_reports' => 'PDF Reports',
        'pdf_reports_desc' => 'PDF reports are print-ready documents including all intervention information, parts used and signatures',
        'csv_imports' => 'CSV Imports',
        'csv_imports_desc' => 'The CSV file must use semicolon (;) as separator. An example file is available on the import page',
        'ical_exports' => 'iCal Exports',
        'ical_exports_desc' => 'iCal export available in the Calendar view for synchronization with Outlook/Google Calendar',
        'generate' => 'Generate',
        'enter_id_warning' => 'Please enter a task number or ID',
        
        // ========== EMAIL TEMPLATES ==========
        'preventive_alert_subject' => '⚠️ GMAO ALERT - Preventive maintenance due',
        'preventive_maintenance_required' => '⚠️ Preventive Maintenance Required',
        'due_date' => 'Due date',
        'view_in_gmao' => 'View in GMAO',
        'automatic_message' => 'Automatic message sent by Industrial GMAO',
        'stock_alert_subject' => '📦 GMAO ALERT - Critical stock',
        'critical_stock_alert' => '📦 Critical stock alert',
        'part_reached_threshold' => 'The following part has reached its minimum threshold',
        'minimum_threshold' => 'Minimum threshold',
        'view_stock' => 'View stock',
        'critical_intervention_subject' => '🚨 URGENT - Critical intervention',
        'new_critical_intervention' => '🚨 URGENCY - New critical intervention',
        'view_intervention' => 'View intervention',
        'immediate_action_required' => 'Automatic GMAO notification - Immediate action required',
        'weekly_report_subject' => '📊 GMAO Weekly Report - Week',
        'weekly_activity_report' => '📊 GMAO Activity Report',
        'period' => 'Period',
        'activity_interventions' => 'Interventions',
        'new_equipment_count' => 'New equipment',
        'access_dashboard' => 'Access Dashboard',
        'remaining_quantity' => 'Remaining quantity',
        
        // ========== PLANNING & CALENDAR ==========
        'planning_title' => 'Interventions Planning',
        'calendar_view' => 'Calendar View',
        'previous_day' => 'Previous Day',
        'next_day' => 'Next Day',
        'today' => 'Today',
        'all_technicians' => 'All Technicians',
        'week_navigation' => 'Week Navigation',
        'total_today' => 'Total today',
        'interventions_for' => 'Interventions for',
        'filtered_by' => 'Filtered by',
        'filtered_by_status' => 'Filtered by status',
        'clear_filters' => 'Clear filters',
        'no_interventions_planned' => 'No interventions planned for this day',
        'plan_intervention' => 'Plan an intervention',
        'non_horaire' => 'No time',
        'week_view' => 'Week View',
        'day_view' => 'Day View',
        'month_view' => 'Month View',
        'export_ical' => 'Export iCal',
        'click_event_details' => 'Click on an event to see details',
        'error_update_date' => 'Error updating the date',
        'report_available' => 'Report available',
        'planned_duration' => 'Planned duration',
        'scheduled_time' => 'Scheduled time',
        'confirm_assignment' => 'Confirm Assignment',
        'select_technician' => 'Select a technician',
        'select_technician_warning' => 'Please select a technician',
        'assign_technician' => 'Assign Technician',
        'workload' => 'Workload',
        'interventions_today' => 'interventions today',
        'no_specialty' => 'No specialty',
        
        // ========== MOBILE INTERFACE ==========
        'welcome' => 'Welcome',
        'online' => 'Online',
        'offline' => 'Offline',
        'home' => 'Home',
        'my_interventions' => 'My Interventions',
        'view_all' => 'View all',
        'no_interventions_assigned' => 'No interventions assigned',
        'scan_qr_code' => 'Scan QR Code',
        'scan_qr_desc' => 'Scan the QR code on the equipment',
        'scan' => 'Scan',
        'or_enter_manually' => 'Or enter manually',
        'equipment_code' => 'Equipment code',
        'equipment_found' => 'Equipment found',
        'equipment_not_found' => 'Equipment not found',
        'connection_error' => 'Connection error',
        'scan_again' => 'Scan again',
        'scan_another' => 'Scan another',
        'report_problem' => 'Report a problem',
        'equipment_code_or_id' => 'Equipment code or ID',
        'recent_equipment' => 'Recent equipment',
        'camera_error' => 'Unable to access camera. Please check permissions.',
        'enter_code_warning' => 'Please enter an equipment code or ID',
        'no_interventions_found' => 'No interventions found',
        'scan_qr_position' => 'Center the QR code in the frame',
        
        // ========== MISCELLANEOUS & COMMON ==========
        'assign' => 'Assign',
        'unassigned' => 'Unassigned',
        'revision' => 'Revision',
        'repair' => 'Repair',
        'installation' => 'Installation',
        'inspection' => 'Inspection',
        'other' => 'Other',
        'preventive_maintenance_short' => 'Preventive Maint.',
        'minutes' => 'minutes',
        'seconds' => 'seconds',
        'and' => 'and',
        'or' => 'or',
        'download' => 'Download',
        'upload' => 'Upload',
        'refresh' => 'Refresh',
        'print' => 'Print',
        'clear' => 'Clear',
        'loading' => 'Loading...',
        'error' => 'Error',
        'success' => 'Success',
        'create' => 'Create',
        'update' => 'Update',
        'status_updated' => 'Status updated successfully',
        'technician_assigned' => 'Technician assigned successfully',
        'intervention_completed' => 'Intervention completed successfully',
        'reactivated' => 'Reactivated',
        'remaining' => 'remaining',
        'url_to_scan' => 'URL to scan',
        'copy_url' => 'Copy URL',
        'test' => 'Test',
        'wifi_instruction' => 'Your smartphone must be on the same Wi-Fi as this computer',
        'url_copied' => 'URL copied!',
        
        // ========== DATABASE STATUS MAPPING ==========
        'pending' => 'Pending',
        'in_progress' => 'In Progress',
        'completed' => 'Completed',
        'closed' => 'Closed',
        'depannage' => 'Repair',
        'maintenance_preventive' => 'Preventive Maintenance',
        'controle' => 'Inspection',
        'autre' => 'Other',

        // ========== CRITICALITY MATRIX ==========
        'criticality_matrix' => 'Criticality Matrix',
        'criticality_heatmap' => 'Criticality Matrix',
        'legend' => 'Legend',
        'probability_scale' => 'Probability scale',
        'severity_scale' => 'Severity scale',
        'very_low' => 'Very low',
        'low' => 'Low',
        'medium' => 'Medium',
        'high' => 'High',
        'very_high' => 'Very high',
        'negligible' => 'Negligible',
        'minor' => 'Minor',
        'moderate' => 'Moderate',
        'seriou' => 'Serious',
        'critical' => 'Critical',
        'criticality_levels' => 'Criticality levels',
        'low_criticality' => 'Low criticality (score 1-4)',
        'medium_criticality' => 'Medium criticality (score 5-9)',
        'high_criticality' => 'High criticality (score 10-15)',
        'very_high_criticality' => 'Very high criticality (score 16-25)',
        'tooltip_instruction' => 'Hover over a cell to see the list of equipment.',
        'equipment_list_with_scores' => 'Equipment list with scores',
        'code' => 'Code',
        'name' => 'Name',
        'probability' => 'Probability',
        'severity' => 'Severity',
        'criticality' => 'Criticality',
        'no_equipment' => 'No equipment',
    ];
    
    return $translations[$key] ?? $key;
}

/**
 * Get the current language code.
 * Hardcoded to 'en' (English) as per project policy.
 * 
 * @return string
 */
function getCurrentLanguage() {
    return 'en';
}

/**
 * Set the user's preferred language.
 * Note: Kept for backward compatibility, but always forces English.
 * 
 * @param string $language The requested language code.
 * @return bool Always true.
 */
function setLanguage($language) {
    return true;
}